# Generated by Django 4.1 on 2022-09-07 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('friend_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_by', to=settings.AUTH_USER_MODEL)),
                ('my_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
