# Generated by Django 4.1 on 2022-09-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_friendmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendModel',
            new_name='FollowAndFollowingModel',
        ),
    ]
