# Generated by Django 4.1 on 2022-11-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_messagefriendmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ManyToManyField(to='users.profileimage'),
        ),
    ]
