# Generated by Django 4.1 on 2022-08-23 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='read_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to=settings.AUTH_USER_MODEL, verbose_name='Oqigan  Foydalanuvchi:'),
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='write_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_by', to=settings.AUTH_USER_MODEL, verbose_name='Yozgan Foydalanuvchi:'),
        ),
    ]
