# Generated by Django 4.1 on 2022-09-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.ImageField(upload_to='post_image/')),
                ('post_title', models.CharField(default='', max_length=300)),
                ('create_by', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
