# Generated by Django 4.1 on 2022-11-22 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storymodel',
            name='seen_user',
            field=models.ManyToManyField(related_name='seen_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storymodel',
            name='story_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='readedpost',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='readedpost',
            name='post',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='feed.postmodel'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='like',
            field=models.ManyToManyField(related_name='like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='post_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='following_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='notification_visible_to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_visible_to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='post_like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_like', to='feed.postmodel'),
        ),
        migrations.AddField(
            model_name='favoriteposts',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favoriteposts',
            name='favorite_post',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='feed.postmodel'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='create_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='feed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed', to='feed.postmodel'),
        ),
    ]
