# Generated by Django 4.1 on 2022-11-22 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_postmodel_post_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='post_type',
        ),
    ]
