# Generated by Django 4.1 on 2022-10-02 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0007_alter_commentmodel_create_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_or_like', models.IntegerField(choices=[(0, 'LIKE'), (1, 'POST')], default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('following_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following_user', to=settings.AUTH_USER_MODEL)),
                ('notification_visible_to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_visible_to_user', to=settings.AUTH_USER_MODEL)),
                ('post_like', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_like', to='feed.postmodel')),
            ],
        ),
    ]
