# Generated by Django 4.1 on 2022-10-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_notificationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='follow_or_like',
            field=models.IntegerField(choices=[(0, 'LIKE'), (1, 'FOLLOWING')], default=0),
        ),
    ]
