# Generated by Django 4.1 on 2022-10-02 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0009_alter_notificationmodel_follow_or_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='following_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='post_like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_like', to='feed.postmodel'),
        ),
    ]
