# Generated by Django 4.1 on 2022-10-03 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0010_alter_notificationmodel_following_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritePosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('favorite_post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='feed.postmodel')),
            ],
        ),
    ]
